# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "{build}"

configuration: 
  - Release
  - Debug

platform:
  - x86
  - x64
  - Any CPU

branches:
  only:
    - master

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug
    - platform: Any CPU
      configuration: Debug

assembly_info:
  patch: false
  
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  
skip_tags: true

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
  
build:
  parallel: true
  verbosity: detailed

environment:
  covfile: .\coverage-$Env:PLATFORM.xml
  covdll: .\UnitTest\bin\net46\Test.dll

test: 
  assemblies:
    only:
      - '**\*.Test.dll'

before_test:
  - Write-Host "Coverage file: $covfile DLL: $covdll"

test_script:
  - OpenCover.Console.exe -log:"All" -register:"user" -target:"%xunit20%\xunit.console.exe" -targetargs:"$covdll -verbose -noshadow" -output:"$covfile"
  - codecov -f "$covfile"
