# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "{build}"

configuration: Release

platform:
  - x86
  - x64

branches:
  only:
    - master

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug
  exclude:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

assembly_info:
  patch: false
  
cache:
  - packages -> **\packages.config

skip_tags: true

test: on

init:
  - git config --global core.autocrlf input

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: detailed
  
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"UnitTest\bin\Release\net46\Test.dll -noshadow" -output:"coverage.xml"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
