# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "{build}"

configuration: 
  - Release
  - Debug

platform:
  - Any CPU

branches:
  only:
    - master

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug
    - platform: Any CPU
      configuration: Debug

assembly_info:
  patch: false
  
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  
skip_tags: true

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  
build:
  parallel: true
  verbosity: detailed

test: 
  assemblies:
    only:
      - '**\Test.dll'

# generate coverage report
after_test:
  - ps: if ($env:configuration -Match "Debug" -and $Env:PLATFORM -Match "Any CPU") { .\coverage.ps1; codecov -f "coverage.xml"}
