# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: "{build}"

configuration: 
  - Release
  - Debug

platform:
  - x86
  - x64
  - Any CPU

branches:
  only:
    - master

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug
    - platform: Any CPU
      configuration: Debug

assembly_info:
  patch: false
  
cache:
  - packages -> **\packages.config

skip_tags: true

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
  
build:
  parallel: true
  verbosity: detailed

test: 
  assemblies:
    only:
      - '**\*.Test.dll'

before_test:
  - $covfile = ".\coverage-$Env:PLATFORM.xml"
  - Write-Host "Coverage file: $covfile"

test_script:
  - OpenCover.Console.exe -log:"All" -register:"user" -target:"%xunit20%\xunit.console.exe" -targetargs:".\UnitTest\bin\Release\net46\Test.dll -verbose -noshadow" -output:"$covfile"
  - codecov -f "$covfile"
